// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKHN0-Cj2CzEfHjBZlzzUuVKci5Z8hjKM',
    appId: '1:580607156889:web:d5a85b5b042425508ace08',
    messagingSenderId: '580607156889',
    projectId: 'socianity-15f89',
    authDomain: 'socianity-15f89.firebaseapp.com',
    storageBucket: 'socianity-15f89.firebasestorage.app',
    measurementId: 'G-4358K98FTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_T-37IPuht_cpQ3DvqaAzMuTBSrULEjw',
    appId: '1:580607156889:android:83040d92ca5e69038ace08',
    messagingSenderId: '580607156889',
    projectId: 'socianity-15f89',
    storageBucket: 'socianity-15f89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWdBhyzg8sWwms6J3TxGRayLD_NDv0HWE',
    appId: '1:580607156889:ios:f6fd17bea29155ac8ace08',
    messagingSenderId: '580607156889',
    projectId: 'socianity-15f89',
    storageBucket: 'socianity-15f89.firebasestorage.app',
    iosBundleId: 'com.example.socianity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWdBhyzg8sWwms6J3TxGRayLD_NDv0HWE',
    appId: '1:580607156889:ios:f6fd17bea29155ac8ace08',
    messagingSenderId: '580607156889',
    projectId: 'socianity-15f89',
    storageBucket: 'socianity-15f89.firebasestorage.app',
    iosBundleId: 'com.example.socianity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKHN0-Cj2CzEfHjBZlzzUuVKci5Z8hjKM',
    appId: '1:580607156889:web:eeaec835363167488ace08',
    messagingSenderId: '580607156889',
    projectId: 'socianity-15f89',
    authDomain: 'socianity-15f89.firebaseapp.com',
    storageBucket: 'socianity-15f89.firebasestorage.app',
    measurementId: 'G-CER4RVRDVP',
  );
}
